---
title: "raw_poststratification"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{raw_poststratification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(tidymrp)
```

<!-- ```{r} -->
<!-- data(example_survey) -->
<!-- data(example_census) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- example_survey <- example_survey %>% -->
<!--   mutate(strata_region_gender = paste("region:", region, "gender:", gender)) -->
<!-- example_census <- example_census %>% -->
<!--   mutate(strata_region_gender = paste("region:", region, "gender:", gender)) -->
<!-- survey_strata_weights <- tidymrp::calculate_survey_strata_weights(example_survey, example_census, strata_region_gender, n) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- example_survey <- example_survey %>% -->
<!--   left_join(survey_strata_weights %>% -->
<!--               select(strata_region_gender, survey_strata_weight)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- example_survey -->
<!-- ``` -->

<!-- ```{r} -->
<!-- calculate_raised_totals(survey = example_survey, survey_strata_weights = survey_strata_weights, strata = strata_region_gender, results_by = region, dependent_variable = non_negative_response) -->
<!-- ``` -->


